---
title: "Academic work"

---

My ResearchGate page is [here](https://www.researchgate.net/profile/Davide-Murari).

### Published works

- Celledoni, E., Çokaj, E., Leone, A., Murari, D., & Owren, B. (2022). Lie Group integrators for mechanical systems. International Journal of Computer Mathematics, 99(1), 58-88.
- Celledoni, E., Leone, A., Murari, D., Owren, B., (2022). Learning Hamiltonians of constrained mechanical systems. Journal of Computational and Applied Mathematics, 114608, ISSN 0377-0427, https://doi.org/10.1016/j.cam.2022.114608

### Preprints

- Celledoni, E., Cokaj, E., Leone, A., Murari, D., & Owren, B. (2021). Dynamics of the N-fold Pendulum in the framework of Lie Group Integrators. arXiv preprint arXiv:2109.12325.
- Celledoni, E., Murari, D., Owren, B., Schönlieb, C-B., Sherry, F., (2022). Dynamical systems' based neural networks. 
arXiv preprint arXiv:2210.02373

### Talks

- SciCADE, Reykjavík, 28-07-2022, "Structure preserving neural networks coming from ODE models", [**SLIDES**](https://slides.com/davidemurari/neural-networks-scicade2022/fullscreen)
- One day – Young Researchers Seminars, Maths Applications & Models,"Learning Hamiltonians of constrained mechanical systems", 08-07-2022 [**SLIDES**](https://slides.com/davidemurari/constrained-hamiltonians-verona/fullscreen)
- DNA Seminar NTNU, "Neural networks modelled by dynamical systems", 20-06-2022 [**SLIDES**](https://slides.com/davidemurari/dna-seminar-2022/fullscreen)
- Math Meets Industry, Trondheim, 02-06-2022, "Structured neural networks motivated by dynamical systems", [**SLIDES**](https://slides.com/davidemurari/talk-mmi/fullscreen)
- Machine Learning and Dynamical Systems Seminar, Turing Institute, 05-05-2022, "Learnings Hamiltonians of constrained mechanical systems", [**SLIDES**](https://slides.com/davidemurari/constrained-hamiltonian/fullscreen)
- Veronesi Tutti Math Seminar, 06-04-2022, "Some connections between dynamical systems and neural networks", [**SLIDES**](https://slides.com/davidemurari/robustness-of-neural-networks)
- MAGIC 2022, "Robustness of neural networks for classification problems", [**SLIDES**](https://slides.com/davidemurari/robustnessmagic2022)
- Workshop "Computational Mathematics and Machine Learning", "Learning the Hamiltonian of some constrained mechanical systems": [**SLIDES**](https://davidemurari.com/wp-content/uploads/2022/02/Learning_Some_constrained_Hamiltonian_systems__Leiden_.pdf)
- NUMDIFF-16, "Learning the Hamiltonian of some classes of mechanical systems": [**SLIDES**](https://davidemurari.com/wp-content/uploads/2022/02/Slides_Learning_Hamiltonian_systems.pdf)
- DNA Seminar NTNU, "Lie group integrator’s approach to the N-fold pendulum": [**SLIDES**](https://davidemurari.com/wp-content/uploads/2022/02/SLIDEs_Lie_Group_Methods___NFold.pdf)
- MAGIC 2021, "Lie group integrator’s approach to the N-fold pendulum": [**SLIDES**](https://davidemurari.com/wp-content/uploads/2022/02/Dynamics_N_fold_pendulum_with_Lie_group_integrators.pdf)